name: Run E2E Tests

on:
  workflow_run:
    workflows: ['Run Unit Tests']
    types:
      - completed

  pull_request:
    branches: ['main']

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: docker
          POSTGRES_DB: fast-feet
          PGDATA: /data/postgres

      cache:
        image: redis
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci

      - run: npm run test:e2e
        env:
          JWT_PRIVATE_KEY: ${{ secrets.JWT_PRIVATE_KEY }}
          JWT_PUBLIC_KEY: ${{ secrets.JWT_PUBLIC_KEY }}
          DATABASE_URL: 'postgresql://postgres:docker@localhost:5432/fast-feet?schema=public'
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          AWS_BUCKET_NAME: 'fast-feet-api-test'
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          MAIL_USER: ${{ secrets.MAIL_PASS }}
          MAIL_PASS: ${{ secrets.MAIL_USER }}
          MAIL_FROM: 'test@example.com'
